# Generated by Django 5.2.1 on 2025-05-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_alter_issue_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('road', 'Road Issue'), ('water', 'Water Issue'), ('electricity', 'Electricity Issue'), ('environment', 'Environment Issue'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
