# Generated by Django 5.2.1 on 2025-05-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_alter_issue_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('road', 'Road Issue'), ('water', 'Water Issue'), ('electricity', 'Electricity Issue'), ('environment', 'Environment Issue'), ('other', 'Other'), ('select_category', 'Select cateory')], default='select_category', max_length=30),
        ),
    ]
