# Generated by Django 5.2.1 on 2025-05-19 05:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
